/**
 * THE WHOLE WORLD OF MUSIC, as far as one file can carry it.
 *
 * Chris: "I want way more fucking options... I'm talking everything, like,
 * world music, everything."
 *
 * Every genre carries a `kit` — the instruments and production that actually
 * define it. That is not decoration, it is the reason this file exists.
 * MiniMax's caption is the single biggest lever on how a song comes out, and
 * "Afrobeats" on its own produces generic pop. "Afrobeats, talking drum,
 * shekere, log drum bass, horn stabs" produces Afrobeats. The picker writes the
 * caption, so the picker has to know what the music is made of.
 *
 * Grouped rather than one flat list. Three hundred items in a single dropdown
 * is not more choice, it is a wall.
 *
 * Written with respect: these are living traditions belonging to real people
 * and places, so they are named properly rather than lumped into "world".
 */

export const GENRE_GROUPS = {
  'Rock': [
    { name: 'Rock', kit: 'electric guitars, bass, live drum kit, room sound' },
    { name: 'Classic rock', kit: 'overdriven guitars, Hammond organ, big live drums' },
    { name: 'Hard rock', kit: 'thick distorted riffs, pounding kit, howling vocals' },
    { name: 'Blues rock', kit: 'dirty guitar, walking bass, slide, tambourine' },
    { name: 'Southern rock', kit: 'twin lead guitars, slide, piano, gospel-ish backing' },
    { name: 'Garage rock', kit: 'fuzz guitar, cheap organ, raw overloaded drums' },
    { name: 'Psychedelic rock', kit: 'phased guitars, sitar drone, tape echo, swirling organ' },
    { name: 'Progressive rock', kit: 'odd meters, Mellotron, synth suites, virtuoso drumming' },
    { name: 'Punk', kit: 'buzzsaw guitar, breakneck drums, shouted vocals, no polish' },
    { name: 'Post-punk', kit: 'chorused bass leading, angular guitar, cold drums, reverb' },
    { name: 'Grunge', kit: 'sludgy detuned guitar, loud-quiet dynamics, raw howl' },
    { name: 'Indie rock', kit: 'jangly guitars, unfussy drums, close honest vocal' },
    { name: 'Shoegaze', kit: 'walls of reverbed guitar, buried vocal, endless sustain' },
    { name: 'Emo', kit: 'clean-to-loud guitars, urgent vocal, cracked delivery' },
    { name: 'Surf rock', kit: 'spring-reverb twang guitar, tom-heavy drums, organ' },
    { name: 'Rockabilly', kit: 'slapback echo, upright bass slap, hollowbody twang' },
    { name: 'Stoner rock', kit: 'downtuned fuzz riffs, huge drums, hazy vocal' },
    { name: 'Math rock', kit: 'tapped guitar figures, shifting meters, tight kit' },
  ],
  'Metal': [
    { name: 'Heavy metal', kit: 'twin guitars, galloping bass, soaring vocal' },
    { name: 'Thrash metal', kit: 'downpicked riffs, double kick, barked vocal' },
    { name: 'Death metal', kit: 'tremolo riffs, blast beats, guttural growl' },
    { name: 'Black metal', kit: 'raw tremolo guitar, blast beats, shrieked vocal, cold reverb' },
    { name: 'Doom metal', kit: 'slow crushing riffs, cavernous drums, mournful vocal' },
    { name: 'Sludge metal', kit: 'filthy downtuned riffs, dragging tempo, screamed vocal' },
    { name: 'Power metal', kit: 'fast twin leads, orchestral keys, operatic vocal' },
    { name: 'Symphonic metal', kit: 'full orchestra with distorted guitars, soprano lead' },
    { name: 'Folk metal', kit: 'fiddle and pipes over distorted guitars, gang vocals' },
    { name: 'Metalcore', kit: 'breakdowns, screamed verses, sung choruses' },
    { name: 'Nu metal', kit: 'downtuned seven-string riffs, hip hop drums, rapped verses' },
    { name: 'Djent', kit: 'palm-muted polyrhythmic riffs, precise kit, ambient leads' },
    { name: 'Industrial metal', kit: 'machine drums, sampled noise, processed vocal' },
  ],
  'Blues': [
    { name: 'Delta blues', kit: 'resonator slide guitar, foot stomp, weathered voice' },
    { name: 'Chicago blues', kit: 'amplified harmonica, electric guitar, piano, shuffle kit' },
    { name: 'Electric blues', kit: 'stinging lead guitar, walking bass, brushed shuffle' },
    { name: 'Acoustic country blues', kit: 'fingerpicked guitar, bottleneck slide, foot' },
    { name: 'Jump blues', kit: 'honking sax section, boogie piano, swinging kit' },
    { name: 'Texas blues', kit: 'stinging overdriven Strat, tight rhythm section' },
    { name: 'Piedmont blues', kit: 'ragtime-style fingerpicking, warm easy vocal' },
    { name: 'Gospel blues', kit: 'slide guitar, tambourine, testifying vocal' },
  ],
  'Country & Americana': [
    { name: 'Country', kit: 'acoustic guitar, pedal steel, fiddle, brushed snare' },
    { name: 'Outlaw country', kit: 'gritty electric, walking bass, weathered baritone' },
    { name: 'Honky tonk', kit: 'pedal steel, barroom piano, shuffle kit, crying vocal' },
    { name: 'Bluegrass', kit: 'banjo, mandolin, fiddle, upright bass, high tenor harmony' },
    { name: 'Old-time / Appalachian', kit: 'clawhammer banjo, fiddle, foot, close harmony' },
    { name: 'Alt-country', kit: 'reverbed twang, loose drums, plainspoken vocal' },
    { name: 'Country ballad', kit: 'slow pedal steel, piano, brushes, intimate vocal' },
    { name: 'Western swing', kit: 'swinging fiddle and steel, jazz chords, upright bass' },
    { name: 'Cajun', kit: 'accordion, fiddle, triangle, French vocal' },
    { name: 'Zydeco', kit: 'accordion, rubboard, driving backbeat' },
    { name: 'Americana', kit: 'acoustic guitar, dobro, brushed kit, harmony vocals' },
    { name: 'Cowboy / western', kit: 'gut-string guitar, wide harmonies, open-range space' },
    { name: 'Country rock', kit: 'electric twang, steel, solid backbeat' },
  ],
  'Folk & Singer-songwriter': [
    { name: 'Folk', kit: 'acoustic guitar, upright bass, quiet close vocal' },
    { name: 'Singer-songwriter', kit: 'fingerpicked guitar or piano, honest intimate vocal' },
    { name: 'Indie folk', kit: 'layered acoustic guitars, group harmonies, brushed drums' },
    { name: 'Freak folk', kit: 'odd tunings, autoharp, bowed saw, strange harmony' },
    { name: 'Protest folk', kit: 'strummed guitar, harmonica rack, unvarnished vocal' },
    { name: 'Sea shanty', kit: 'unaccompanied gang vocals, concertina, stamping feet' },
    { name: 'Spirituals', kit: 'unaccompanied call and response, hand claps, deep harmony' },
  ],
  'Soul, R&B & Funk': [
    { name: 'Soul', kit: 'horn section, electric piano, tight rhythm, gospel-trained voice' },
    { name: 'Motown', kit: 'melodic bass, tambourine on every beat, strings, backing trio' },
    { name: 'Southern soul', kit: 'greasy horns, Hammond, snapping snare, raw voice' },
    { name: 'Neo-soul', kit: 'Rhodes, loose behind-the-beat drums, jazz chords' },
    { name: 'Contemporary R&B', kit: 'programmed drums, warm pads, stacked harmonies' },
    { name: 'Quiet storm', kit: 'soft electric piano, fretless bass, breathy vocal' },
    { name: 'Funk', kit: 'slap bass, wah guitar, tight horn stabs, hard drum break' },
    { name: 'P-funk', kit: 'synth bass, wah clav, layered chants, space effects' },
    { name: 'Disco', kit: 'four-on-the-floor, string stabs, octave bass, hi-hats' },
    { name: 'Boogie', kit: 'synth bass, gated snare, glossy chords' },
    { name: 'Gospel', kit: 'Hammond organ, piano, full choir, driving tambourine' },
    { name: 'Doo-wop', kit: 'close vocal harmony, triplet piano, brushed drums' },
    { name: 'Blue-eyed soul', kit: 'horns, organ, earnest strained vocal' },
  ],
  'Hip hop': [
    { name: 'Boom bap', kit: 'dusty chopped sample, hard snare, upright bass loop' },
    { name: 'Trap', kit: '808 sub, rolling hi-hats, sparse dark melody' },
    { name: 'Drill', kit: 'sliding 808s, skittering hats, cold minor melody' },
    { name: 'G-funk', kit: 'high whining synth lead, deep bass, slow funk groove' },
    { name: 'Southern rap', kit: 'heavy 808 kick, snapping snare, chant hooks' },
    { name: 'Chopped and screwed', kit: 'slowed pitch-dropped sample, stuttered chops, deep sub' },
    { name: 'Conscious hip hop', kit: 'jazz sample, live bass, clear front vocal' },
    { name: 'Jazz rap', kit: 'upright bass, brushed drums, muted trumpet, sampled piano' },
    { name: 'Lo-fi hip hop', kit: 'vinyl crackle, warm Rhodes, soft dusty drums' },
    { name: 'Cloud rap', kit: 'washed reverb pads, distant vocal, slow drums' },
    { name: 'Horrorcore', kit: 'dissonant strings, hard drums, menacing delivery' },
    { name: 'Grime', kit: 'square-wave bass, 140 bpm skippy drums, rapid delivery' },
    { name: 'UK drill', kit: 'gliding 808, dark strings, clipped delivery' },
    { name: 'Old school hip hop', kit: 'live break, scratch, party call and response' },
    { name: 'Phonk', kit: 'memphis vocal chops, cowbell bass, distorted drums' },
  ],
  'Pop': [
    { name: 'Pop', kit: 'bright synths, punchy programmed drums, layered hooks' },
    { name: 'Synth-pop', kit: 'analog synth bass, gated drums, cold bright pads' },
    { name: 'Power pop', kit: 'chiming guitars, big harmonies, snappy drums' },
    { name: 'Dream pop', kit: 'reverbed guitar, soft pads, breathy distant vocal' },
    { name: 'Bedroom pop', kit: 'lo-fi guitar, drum machine, close untreated vocal' },
    { name: 'Hyperpop', kit: 'pitched-up vocal, distorted bass, sugary maximal synths' },
    { name: 'Art pop', kit: 'unusual textures, orchestral touches, adventurous production' },
    { name: 'Teen pop', kit: 'glossy production, huge chorus, doubled vocals' },
    { name: 'Baroque pop', kit: 'harpsichord, strings, French horn, chamber arrangement' },
    { name: 'City pop', kit: 'slick fretless bass, glossy chords, eighties studio sheen' },
  ],
  'Electronic': [
    { name: 'House', kit: 'four-on-the-floor kick, filtered loops, warm bass' },
    { name: 'Deep house', kit: 'soft chords, rolling bass, brushed hats' },
    { name: 'Techno', kit: 'relentless kick, metallic percussion, hypnotic loop' },
    { name: 'Trance', kit: 'supersaw lead, rolling bass, long builds and breakdowns' },
    { name: 'Drum and bass', kit: 'breakbeats at 174, deep sub bass, tight edits' },
    { name: 'Jungle', kit: 'chopped amen break, heavy sub, ragga vocal chops' },
    { name: 'Dubstep', kit: 'half-time drums, wobbling bass, deep space' },
    { name: 'UK garage', kit: 'shuffled two-step drums, clipped vocal, warm sub' },
    { name: 'Breakbeat', kit: 'funky broken drums, big bass, sampled stabs' },
    { name: 'Ambient', kit: 'slow evolving pads, no drums, deep space and air' },
    { name: 'Downtempo / trip hop', kit: 'slow heavy drums, dusty samples, smoky vocal' },
    { name: 'IDM', kit: 'intricate glitched drums, odd melodic synths' },
    { name: 'Synthwave', kit: 'arpeggiated bass, gated reverb drums, neon leads' },
    { name: 'Vaporwave', kit: 'slowed sample, chorus-drenched keys, tape wobble' },
    { name: 'EDM / big room', kit: 'huge drop, sidechained supersaws, festival kick' },
    { name: 'Future bass', kit: 'pitched vocal chops, detuned saw swells, trap drums' },
    { name: 'Industrial', kit: 'clanging metal percussion, distorted synth, harsh vocal' },
    { name: 'Chiptune', kit: 'square and pulse waves, noise-channel drums' },
    { name: 'Drone', kit: 'sustained tones, slow harmonic shifts, no rhythm' },
    { name: 'Lounge / exotica', kit: 'vibraphone, bongos, bird calls, easy strings' },
  ],
  'Jazz': [
    { name: 'Jazz', kit: 'upright bass, brushed kit, piano comping, horn lead' },
    { name: 'Bebop', kit: 'fast walking bass, ride cymbal, intricate horn lines' },
    { name: 'Swing / big band', kit: 'full horn sections, four-to-the-bar rhythm, shout chorus' },
    { name: 'Cool jazz', kit: 'muted trumpet, soft brushes, relaxed restrained lines' },
    { name: 'Hard bop', kit: 'punchy horns, gospel-tinged piano, driving ride' },
    { name: 'Modal jazz', kit: 'open vamps, sparse piano, exploratory sax' },
    { name: 'Free jazz', kit: 'no fixed meter, collective improvisation, extended technique' },
    { name: 'Jazz fusion', kit: 'electric piano, fretless bass, complex meters, synth lead' },
    { name: 'Smooth jazz', kit: 'soprano sax lead, glossy keys, soft programmed groove' },
    { name: 'Gypsy jazz', kit: 'acoustic lead guitar, la pompe rhythm, violin' },
    { name: 'Vocal jazz standard', kit: 'piano trio, brushes, expressive phrasing' },
    { name: 'Dixieland', kit: 'collective front-line horns, banjo, tuba, snare' },
    { name: 'Acid jazz', kit: 'Hammond, funk break, wah guitar, live horns' },
  ],
  'Reggae & Caribbean': [
    { name: 'Reggae', kit: 'one-drop drums, deep bass, skanking offbeat guitar, organ bubble' },
    { name: 'Roots reggae', kit: 'meditative bassline, nyabinghi drums, horns, spiritual vocal' },
    { name: 'Dub', kit: 'stripped bass and drums, huge spring reverb, tape delay throws' },
    { name: 'Dancehall', kit: 'digital riddim, sparse punchy drums, patois vocal' },
    { name: 'Ska', kit: 'upstroke guitar, walking bass, bright horn section' },
    { name: 'Rocksteady', kit: 'slower ska groove, melodic bass, sweet harmony' },
    { name: 'Soca', kit: 'fast carnival groove, brass, whistles, chanted hooks' },
    { name: 'Calypso', kit: 'steel pan, light percussion, storytelling vocal' },
    { name: 'Zouk', kit: 'syncopated drum machine, glossy synths, Creole vocal' },
    { name: 'Reggaeton', kit: 'dembow rhythm, deep kick, sparse synth hooks' },
  ],
  'Latin America': [
    { name: 'Salsa', kit: 'clave, congas, timbales, piano montuno, brass section' },
    { name: 'Bachata', kit: 'requinto guitar lead, bongo, guira, romantic vocal' },
    { name: 'Merengue', kit: 'fast two-step, tambora, guira, brass' },
    { name: 'Cumbia', kit: 'gaita flute, accordion, guacharaca scraper, steady groove' },
    { name: 'Bossa nova', kit: 'nylon guitar, brushed snare, soft breathy vocal' },
    { name: 'Samba', kit: 'surdo, pandeiro, cavaquinho, layered percussion' },
    { name: 'MPB', kit: 'nylon guitar, rich harmony, warm intimate vocal' },
    { name: 'Tango', kit: 'bandoneon, violin, piano, dramatic rubato' },
    { name: 'Mariachi', kit: 'trumpets, violins, vihuela, guitarron, full-throated vocal' },
    { name: 'Ranchera', kit: 'mariachi backing, slow waltz or bolero, grand vocal' },
    { name: 'Norteno', kit: 'accordion, bajo sexto, polka-derived rhythm' },
    { name: 'Banda', kit: 'full brass and clarinets, tuba bass, snare drive' },
    { name: 'Corrido', kit: 'accordion and bajo sexto, narrative verses' },
    { name: 'Bolero', kit: 'nylon guitar, soft percussion, aching romantic vocal' },
    { name: 'Son cubano', kit: 'tres guitar, bongo, maracas, call and response' },
    { name: 'Latin jazz', kit: 'congas, montuno piano, horns, clave under solos' },
    { name: 'Andean folk', kit: 'panpipes, charango, quena flute, bombo drum' },
    { name: 'Forro', kit: 'accordion, zabumba drum, triangle, dance groove' },
    { name: 'Musica llanera', kit: 'harp, cuatro, maracas, rapid joropo rhythm' },
  ],
  'Africa': [
    { name: 'Afrobeats', kit: 'log drum bass, shakers, bright synth, laid-back vocal' },
    { name: 'Afrobeat (Fela style)', kit: 'long horn riffs, tight funk drums, shekere, organ' },
    { name: 'Highlife', kit: 'interlocking guitars, horns, bright dance groove' },
    { name: 'Soukous', kit: 'fast lead guitar lines, driving sebene, layered percussion' },
    { name: 'Amapiano', kit: 'log drum bass, shakers, jazzy piano chords, wide space' },
    { name: 'Gqom', kit: 'raw broken kicks, minimal dark loops, chanted vocal' },
    { name: 'Kwaito', kit: 'slowed house groove, deep bass, spoken township vocal' },
    { name: 'Mbalax', kit: 'sabar drums, dense polyrhythm, sharp vocal' },
    { name: 'Desert blues / Tuareg', kit: 'hypnotic electric guitar loops, calabash, chanted vocal' },
    { name: 'Juju', kit: 'talking drums, layered guitars, praise vocals' },
    { name: 'Ethio-jazz', kit: 'minor-key horns, organ, loose drums, hypnotic vamp' },
    { name: 'Bikutsi', kit: 'fast balafon patterns, driving percussion' },
    { name: 'Chimurenga', kit: 'mbira-derived guitar lines, gentle groove, message vocal' },
    { name: 'Rai', kit: 'synth and derbouka, wailing melisma, dance groove' },
    { name: 'Gnawa', kit: 'guembri bass lute, iron qraqeb castanets, trance call and response' },
    { name: 'Taarab', kit: 'oud, violin, qanun, Swahili poetic vocal' },
  ],
  'Middle East & North Africa': [
    { name: 'Arabic pop', kit: 'oud, qanun, strings, darbuka, ornamented vocal' },
    { name: 'Classical Arabic / tarab', kit: 'takht ensemble, oud, nay, extended vocal improvisation' },
    { name: 'Dabke', kit: 'mijwiz reed, heavy derbouka, driving line-dance rhythm' },
    { name: 'Chaabi', kit: 'banjo, violin, hand percussion, communal vocal' },
    { name: 'Turkish folk', kit: 'baglama saz, davul drum, zurna, modal melody' },
    { name: 'Anatolian rock', kit: 'saz through fuzz, rock kit, modal riffs' },
    { name: 'Persian classical', kit: 'tar, santur, tombak, poetic vocal with tahrir' },
    { name: 'Israeli / Mizrahi pop', kit: 'oud and synth, darbuka, ornamented vocal' },
  ],
  'South Asia': [
    { name: 'Bollywood / filmi', kit: 'strings, tabla, dholak, big playback vocal' },
    { name: 'Bhangra', kit: 'dhol drum, tumbi, boisterous Punjabi vocal' },
    { name: 'Qawwali', kit: 'harmonium, tabla, hand claps, ecstatic call and response' },
    { name: 'Ghazal', kit: 'harmonium, tabla, sarangi, restrained poetic vocal' },
    { name: 'Hindustani classical', kit: 'sitar or sarod, tanpura drone, tabla, slow alap' },
    { name: 'Carnatic', kit: 'violin, mridangam, tanpura, intricate ornamentation' },
    { name: 'Indian folk fusion', kit: 'bansuri flute, tabla, modern bass and drums' },
    { name: 'Baul', kit: 'ektara drone, khamak, wandering mystic vocal' },
  ],
  'East Asia': [
    { name: 'Mandopop', kit: 'piano and strings, polished ballad production' },
    { name: 'Cantopop', kit: 'lush strings, romantic melody, glossy production' },
    { name: 'K-pop', kit: 'maximal synths, tight programmed drums, layered group vocals' },
    { name: 'J-pop', kit: 'bright chords, busy arrangement, high clear vocal' },
    { name: 'J-rock', kit: 'driving guitars, dramatic melody, urgent vocal' },
    { name: 'Enka', kit: 'shakuhachi, strings, deeply ornamented melancholic vocal' },
    { name: 'Chinese classical', kit: 'guzheng, erhu, dizi flute, pipa' },
    { name: 'Gugak (Korean)', kit: 'gayageum, janggu drum, haegeum, pansori vocal' },
    { name: 'Traditional Japanese', kit: 'koto, shamisen, shakuhachi, taiko' },
    { name: 'Mongolian throat singing', kit: 'morin khuur horsehead fiddle, overtone vocal, wide steppe space' },
  ],
  'Southeast Asia & Pacific': [
    { name: 'Gamelan', kit: 'bronze metallophones, gongs, cyclical interlocking patterns' },
    { name: 'Dangdut', kit: 'tabla-like gendang, flute, swaying dance groove' },
    { name: 'Luk thung', kit: 'khaen reed, strings, expressive rural vocal' },
    { name: 'OPM', kit: 'acoustic guitar, warm band, heartfelt Filipino vocal' },
    { name: 'Hawaiian', kit: 'slack-key guitar, ukulele, steel guitar, gentle falsetto' },
    { name: 'Maori / Pacific', kit: 'group harmony, guitar, hand percussion, chant' },
  ],
  'Europe & folk traditions': [
    { name: 'Celtic / Irish trad', kit: 'fiddle, tin whistle, bodhran, uilleann pipes' },
    { name: 'Scottish folk', kit: 'highland pipes, fiddle, bodhran, strong unison melody' },
    { name: 'Nordic folk', kit: 'nyckelharpa, hardanger fiddle, stark open harmony' },
    { name: 'Klezmer', kit: 'clarinet, violin, accordion, tsimbl, wailing ornament' },
    { name: 'Balkan brass', kit: 'raucous brass band, fast odd meters, big bass drum' },
    { name: 'Polka', kit: 'accordion, tuba, snare, cheerful two-step' },
    { name: 'Fado', kit: 'Portuguese guitarra, classical guitar, aching solo vocal' },
    { name: 'Flamenco', kit: 'nylon guitar, palmas hand claps, cajon, raw cante vocal' },
    { name: 'Chanson', kit: 'accordion, upright bass, piano, conversational vocal' },
    { name: 'Alpine / Volksmusik', kit: 'accordion, brass, yodel, waltz time' },
    { name: 'Russian folk', kit: 'balalaika, bayan accordion, deep choral harmony' },
    { name: 'Romani / gypsy', kit: 'violin, cimbalom, accelerating tempo, virtuoso runs' },
    { name: 'Greek rebetiko', kit: 'bouzouki, baglama, mournful vocal' },
  ],
  'Classical & orchestral': [
    { name: 'Orchestral / film score', kit: 'full orchestra, strings leading, brass swells, timpani' },
    { name: 'Baroque', kit: 'harpsichord, chamber strings, counterpoint' },
    { name: 'Classical era', kit: 'chamber orchestra, clean balanced lines' },
    { name: 'Romantic', kit: 'sweeping strings, expressive rubato, big dynamics' },
    { name: 'Chamber / string quartet', kit: 'two violins, viola, cello, intimate room' },
    { name: 'Solo piano', kit: 'a single piano, pedal, close and unhurried' },
    { name: 'Opera', kit: 'orchestra and trained operatic voice, full dynamic range' },
    { name: 'Choral / sacred', kit: 'full choir, organ, cathedral reverb' },
    { name: 'Minimalism', kit: 'repeating cells, slow phase shifts, marimba and strings' },
    { name: 'Modern classical', kit: 'prepared piano, extended technique, unusual textures' },
    { name: 'Tango nuevo', kit: 'bandoneon, strings, jazz harmony, sharp dynamics' },
  ],
  'Other & experimental': [
    { name: 'Marching band', kit: 'brass, snare line, sousaphone, field drums' },
    { name: 'Barbershop', kit: 'four-part unaccompanied close harmony' },
    { name: 'A cappella', kit: 'voices only, vocal bass and percussion' },
    { name: 'Musical theatre', kit: 'pit orchestra, story-driven vocal, big finish' },
    { name: 'Children’s song', kit: 'simple bright melody, hand claps, easy singalong' },
    { name: 'Christmas / holiday', kit: 'sleigh bells, warm strings, nostalgic harmony' },
    { name: 'Noise', kit: 'harsh feedback, distortion, no fixed pitch' },
    { name: 'Spoken word with music', kit: 'sparse instrumental bed under a speaking voice' },
    { name: 'Field recording collage', kit: 'environmental sound, tape loops, sparse tones' },
    { name: 'New age', kit: 'soft synth pads, flute, water and wind textures' },
  ],
};

export const MOOD_GROUPS = {
  'Driving': ['Gritty and driving', 'Defiant', 'Relentless', 'Urgent', 'Rowdy',
    'Triumphant', 'Swaggering', 'Rebellious', 'Fierce', 'Anthemic', 'Restless'],
  'Heavy': ['Menacing', 'Brooding', 'Ominous', 'Furious', 'Bitter', 'Desperate',
    'Haunted', 'Claustrophobic', 'Apocalyptic', 'Vengeful'],
  'Sad': ['Lonesome', 'Heartbroken', 'Weary', 'Mournful', 'Regretful', 'Wistful',
    'Resigned', 'Homesick', 'Aching', 'Bittersweet'],
  'Tender': ['Warm and slow', 'Intimate', 'Loving', 'Grateful', 'Nostalgic',
    'Comforting', 'Devoted', 'Vulnerable', 'Hopeful', 'Reverent'],
  'Bright': ['Joyful', 'Playful', 'Carefree', 'Celebratory', 'Flirtatious',
    'Sunny', 'Silly', 'Optimistic', 'Wide-eyed'],
  'Cool': ['Laid-back', 'Smoky', 'Late-night', 'Hypnotic', 'Dreamy', 'Woozy',
    'Detached', 'Cocky', 'Smooth', 'Sultry'],
  'Still': ['Peaceful', 'Meditative', 'Sparse', 'Vast', 'Solitary', 'Floating',
    'Frozen', 'Weightless'],
  'Strange': ['Uneasy', 'Surreal', 'Unhinged', 'Chaotic', 'Mischievous',
    'Otherworldly', 'Feverish'],
  'Spiritual': ['Prayerful', 'Ecstatic', 'Searching', 'Testifying', 'Mystical',
    'Mourning', 'Praise-filled'],
};

export const VOICE_GROUPS = {
  'Male': [
    'Gravelly male', 'Smooth male baritone', 'Deep bass male', 'High tenor male',
    'Raspy male', 'Weathered old male', 'Young male', 'Breathy male',
    'Booming male', 'Nasal male', 'Crooning male', 'Male falsetto',
    'Whispered male', 'Growling male', 'Operatic male',
  ],
  'Female': [
    'Powerful female', 'Warm female alto', 'Bright female soprano', 'Husky female',
    'Breathy female', 'Girlish female', 'Weathered female', 'Belting female',
    'Whispered female', 'Female falsetto', 'Operatic female', 'Smoky female contralto',
    'Sweet female', 'Fierce female',
  ],
  'Androgynous & other': [
    'Androgynous voice', 'Childlike voice', 'Robotic vocoded voice',
    'Pitched-up chipmunk voice', 'Pitched-down demonic voice', 'Choirboy voice',
  ],
  'Groups': [
    'Male duet', 'Female duet', 'Mixed duet', 'Male and female trading verses',
    'Full gospel choir', 'Rough gang vocals', 'Close barbershop harmony',
    'Children’s choir', 'Call and response with a crowd',
    'Layered stacked harmonies', 'Unison group chant',
  ],
  'Delivery': [
    'Rapped, laid back', 'Rapped, fast and technical', 'Rapped, aggressive',
    'Half-sung half-spoken', 'Spoken word', 'Preaching and testifying',
    'Yodelling', 'Throat singing', 'Scat singing', 'Melismatic and ornamented',
    'Auto-tuned melodic', 'Screamed', 'Shouted punk delivery', 'Crooned close to the mic',
    'Chanted', 'Wailing', 'Mumbled and slurred',
  ],
  'No vocals': [
    'Instrumental, no vocals', 'Instrumental with wordless humming',
    'Instrumental with occasional vocal samples',
  ],
};

/** Flat lookups, so a saved value keeps working if the groups get reshuffled. */
export const ALL_GENRES = Object.values(GENRE_GROUPS).flat();
export const ALL_MOODS = Object.values(MOOD_GROUPS).flat();
export const ALL_VOICES = Object.values(VOICE_GROUPS).flat();

/** The instruments that make a genre sound like itself. */
export function kitFor(genreName) {
  const hit = ALL_GENRES.find((g) => g.name === genreName);
  return hit ? hit.kit : 'guitar, bass and a live drum kit';
}

export const COUNTS = {
  genres: ALL_GENRES.length,
  moods: ALL_MOODS.length,
  voices: ALL_VOICES.length,
};
