#!/usr/bin/env node
/**
 * Lyricist release builder
 *
 * Bumps build-number.txt → 001, 002, 003…
 * Writes src/buildInfo.js
 * Vite build + electron-builder
 * Output names:
 *   Lyricist 4.2.0.001 Setup.exe
 *   Lyricist 4.2.0.001/   (win-unpacked copy, optional)
 *
 * Usage:
 *   node scripts/release.mjs              # bump + full installer
 *   node scripts/release.mjs --no-bump    # rebuild same build number
 *   node scripts/release.mjs --dir        # unpacked dir only (faster)
 *   node scripts/release.mjs --set 12     # force build number to 012
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const BUILD_FILE = path.join(ROOT, 'build-number.txt');
const BUILD_INFO = path.join(ROOT, 'src', 'buildInfo.js');
const PKG_PATH = path.join(ROOT, 'package.json');

const args = process.argv.slice(2);
const noBump = args.includes('--no-bump');
// One build: every release is Chris's full build, with Ask the Ghost, the Ghost
// Pilot and the native engine in it. --customer makes the stripped installer
// for other people; there the flag is forced OFF below, even if a .env file
// sets it, so a customer can never pick the Ghost up by accident. (--creator
// is still accepted and changes nothing.)
const creator = !args.includes('--customer');
const edition = creator ? ' Creator' : '';
const dirOnly = args.includes('--dir');
const setIdx = args.indexOf('--set');
const forceSet = setIdx >= 0 ? parseInt(args[setIdx + 1], 10) : null;

const pkg = JSON.parse(fs.readFileSync(PKG_PATH, 'utf8'));
const baseVersion = String(pkg.version || '4.2.0').split('.').slice(0, 3).join('.');

function readBuildNum() {
  try {
    const n = parseInt(String(fs.readFileSync(BUILD_FILE, 'utf8')).trim(), 10);
    return Number.isFinite(n) && n > 0 ? n : 1;
  } catch {
    return 1;
  }
}

function writeBuildNum(n) {
  fs.writeFileSync(BUILD_FILE, `${n}\n`, 'utf8');
}

function pad(n) {
  return String(n).padStart(3, '0');
}

let buildNum = readBuildNum();
if (forceSet != null && Number.isFinite(forceSet) && forceSet > 0) {
  buildNum = forceSet;
  writeBuildNum(buildNum);
} else if (!noBump) {
  // If file says 1 and we haven't released yet, use 1 first then next bump is 2.
  // Convention: bump BEFORE each release so first release is 001 when file starts at 0 or we use current then increment after.
  // User wants 001, 002, 003 on each executable turn-in.
  // On first run with file=1 → ship 001, then write 2 for next.
  // If re-running same day with --no-bump, keep number.
  // Default: use current number, then increment file for next time.
}

const buildPad = pad(buildNum);
const fullVersion = `${baseVersion}.${buildPad}`;

// UI always shows clean product version (4.2.0). Build pad is for EXE filenames only.
const buildInfoSrc = `// Auto-generated by scripts/release.mjs — do not hand-edit for releases.
// On-screen product version: ${baseVersion}
// Installer / folder name only: Lyricist ${fullVersion}
export const APP_VERSION = '${baseVersion}';
export const BUILD_NUMBER = '${buildPad}';
export const FULL_VERSION = '${fullVersion}';
/** Shown in UI — never includes .001/.002 build pad */
/** The product name. Never carries a version — that is what APP_VERSION is for,
 *  and "Lyricist 4.2.0" as a NAME was the 420 joke the commercial refactor
 *  removed. Regenerating this file must not put it back. */
export const APP_TITLE = 'Lyricist Pro';
export const WINDOW_TITLE = 'Lyricist Pro';
`;

fs.writeFileSync(BUILD_INFO, buildInfoSrc, 'utf8');
console.log(`\n═══ Lyricist release ${fullVersion} ═══\n`);

// Desktop output folder (user convention). Creator and Customer builds land in
// their own subfolders so Chris can always tell which is which.
const releaseRoot =
  process.env.LYRICIST_RELEASE_DIR ||
  path.join(
    process.env.USERPROFILE || process.env.HOME || ROOT,
    'OneDrive',
    'Desktop',
    'New Releases for Lyricist Pro'
  );
const desktopOut = path.join(releaseRoot, creator ? 'Creator' : 'Customer');

fs.mkdirSync(desktopOut, { recursive: true });

// The installer step (makensis) maps the whole ~430 MB payload through a file
// in TEMP, and C: is nearly full on Chris's machine ("error creating mmap").
// Keep that temp file on the same drive as the output.
const buildTemp = path.join(desktopOut, '.build-temp');
fs.mkdirSync(buildTemp, { recursive: true });

function run(cmd, cmdArgs, opts = {}) {
  console.log(`> ${cmd} ${cmdArgs.join(' ')}`);
  const r = spawnSync(cmd, cmdArgs, {
    cwd: ROOT,
    stdio: 'inherit',
    shell: true,
    env: {
      ...process.env,
      TEMP: buildTemp,
      TMP: buildTemp,
      LYRICIST_FULL_VERSION: fullVersion,
      LYRICIST_BUILD: buildPad,
      // Vite never overrides a variable already in the process, so this wins
      // over any .env file: on for --creator, off for every customer build.
      VITE_FAFO_INTERNAL_BUILD: creator ? 'true' : 'false',
    },
    ...opts,
  });
  if (r.status !== 0) {
    console.error(`Command failed: ${cmd}`);
    process.exit(r.status || 1);
  }
}

// 1) Vite production build
run('npm', ['run', 'build']);

// 1b) The Ghost's real-mouse core, Creator only.
//     package.json extraResources ships build-creator/ as resources/creator.
//     Creator: libnut (the 1 MB native core of nut-js, main.js pilot()) so a
//     lesson replays on the real cursor. Customer: a placeholder and nothing
//     else, so main.js finds no libnut and the pilot stays off.
const creatorStage = path.join(ROOT, 'build-creator');
fs.rmSync(creatorStage, { recursive: true, force: true });
fs.mkdirSync(creatorStage, { recursive: true });
if (creator) {
  // Each piece is optional: a missing one is left out with a warning and the
  // build carries on. The Ghost panel itself needs none of them.
  const skipped = [];
  const libnutSrc = path.join(ROOT, 'node_modules', '@nut-tree-fork', 'libnut-win32', 'build', 'Release');
  if (fs.existsSync(path.join(libnutSrc, 'libnut.node'))) {
    fs.cpSync(libnutSrc, path.join(creatorStage, 'libnut'), {
      recursive: true,
      filter: (p) => !/\.(exp|lib)$/i.test(p),
    });
  } else {
    skipped.push(`Ghost Pilot (real mouse): no ${libnutSrc}\\libnut.node. Run npm install.`);
  }

  // The native audio engine (ASIO + VST3), with the three VC++ runtime DLLs it
  // links against beside it, so it runs on a PC without the redistributable.
  // main.js getJuceEnginePath() looks in resources/creator/engine and copes
  // with it missing, as every customer build does.
  // Not built yet: build it here when CMake and the C++ tools are on this PC,
  // so a Creator build never ships without the engine just because nobody ran
  // cmake first ("LyricistEngine.exe not found" in Settings → VST3).
  const engineDir = path.join(ROOT, 'juce-backend');
  // prebuilt/ is the copy GitHub builds on Windows and commits
  // (.github/workflows/engine.yml), with its VC++ runtime DLLs beside it.
  const prebuilt = path.join(engineDir, 'prebuilt');
  const engineBuilt = () => [
    path.join(prebuilt, 'LyricistEngine.exe'),
    path.join(engineDir, 'build', 'Release', 'LyricistEngine.exe'),
    path.join(engineDir, 'build', 'LyricistEngine.exe'),
    path.join(engineDir, 'build', 'LyricistEngine_artefacts', 'Release', 'Lyricist Engine.exe'),
    path.join(engineDir, 'build', 'LyricistEngine_artefacts', 'Release', 'LyricistEngine.exe'),
  ].find((p) => fs.existsSync(p));
  if (!engineBuilt() && process.platform === 'win32') {
    // CMake ships inside every Visual Studio 2022 install (Build Tools,
    // Community, Pro); vswhere says where that is.
    const vswhere = 'C:\\Program Files (x86)\\Microsoft Visual Studio\\Installer\\vswhere.exe';
    const vs = fs.existsSync(vswhere)
      ? String(spawnSync(`"${vswhere}"`, ['-latest', '-products', '*', '-property', 'installationPath'], { shell: true, encoding: 'utf8' }).stdout || '').trim()
      : '';
    const vsCmake = vs && path.join(vs, 'Common7', 'IDE', 'CommonExtensions', 'Microsoft', 'CMake', 'CMake', 'bin', 'cmake.exe');
    const onPath = spawnSync('where', ['cmake'], { shell: true, encoding: 'utf8' });
    const cmake = onPath.status === 0 ? 'cmake' : vsCmake && fs.existsSync(vsCmake) ? `"${vsCmake}"` : null;
    if (cmake) {
      console.log('\n  Building the native audio engine (first time downloads JUCE, takes a while)...\n');
      const opts = { cwd: engineDir, stdio: 'inherit', shell: true };
      // ASIO needs Steinberg's SDK, which is not in git. Fetch it once into
      // juce-backend/asiosdk (gitignored); without it the engine still builds,
      // on WASAPI only.
      const asioHeader = () => {
        const walk = (d) => { for (const f of fs.readdirSync(d, { withFileTypes: true })) { const p = path.join(d, f.name); if (f.isDirectory()) { const r = walk(p); if (r) return r; } else if (f.name.toLowerCase() === 'iasiodrv.h') return d; } return null; };
        return fs.existsSync(path.join(engineDir, 'asiosdk')) ? walk(path.join(engineDir, 'asiosdk')) : null;
      };
      if (!asioHeader()) {
        spawnSync('powershell', ['-NoProfile', '-Command', `"$ProgressPreference='SilentlyContinue'; Invoke-WebRequest https://www.steinberg.net/asiosdk -OutFile asiosdk.zip; Expand-Archive -Force asiosdk.zip asiosdk; Remove-Item asiosdk.zip"`], opts);
      }
      const asio = asioHeader();
      if (!asio) console.warn('  ASIO SDK could not be fetched: the engine builds with WASAPI only.');
      spawnSync(cmake, ['-B', 'build', '-G', '"Visual Studio 17 2022"', '-A', 'x64', ...(asio ? [`-DASIO_SDK_DIR="${asio.replace(/\\/g, '/')}"`] : [])], opts);
      spawnSync(cmake, ['--build', 'build', '--config', 'Release'], opts);
    }
  }
  const engineExe = engineBuilt() || path.join(engineDir, 'build', 'Release', 'LyricistEngine.exe');
  const redistRoot = 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2022\\BuildTools\\VC\\Redist\\MSVC';
  const crt = fs.existsSync(path.join(prebuilt, 'msvcp140.dll')) ? prebuilt
    : fs.existsSync(redistRoot) && fs.readdirSync(redistRoot)
      .map((v) => path.join(redistRoot, v, 'x64', 'Microsoft.VC143.CRT'))
      .find((p) => fs.existsSync(path.join(p, 'msvcp140.dll')));
  // The prebuilt engine links the C++ runtime in statically: nothing to put
  // beside it. One built here with Visual Studio needs the three DLLs.
  const staticEngine = engineExe === path.join(prebuilt, 'LyricistEngine.exe') && !fs.existsSync(path.join(prebuilt, 'msvcp140.dll'));
  if (!fs.existsSync(engineExe)) {
    skipped.push('Native audio engine (ASIO + VST3): could not build it. Install Visual Studio 2022 Build Tools with "Desktop development with C++" (it brings CMake), then run this again.');
  } else if (staticEngine) {
    const engineStage = path.join(creatorStage, 'engine');
    fs.mkdirSync(engineStage, { recursive: true });
    fs.copyFileSync(engineExe, path.join(engineStage, 'LyricistEngine.exe'));
  } else if (!crt) {
    skipped.push('Native audio engine: the VC++ runtime DLLs were not found (Visual Studio Build Tools, VC\\Redist\\MSVC\\*\\x64\\Microsoft.VC143.CRT).');
  } else {
    const engineStage = path.join(creatorStage, 'engine');
    fs.mkdirSync(engineStage, { recursive: true });
    fs.copyFileSync(engineExe, path.join(engineStage, 'LyricistEngine.exe'));
    for (const dll of ['msvcp140.dll', 'vcruntime140.dll', 'vcruntime140_1.dll']) {
      fs.copyFileSync(path.join(crt, dll), path.join(engineStage, dll));
    }
  }
  for (const s of skipped) console.warn(`\n  LEFT OUT  ${s}`);
  if (skipped.length) console.warn('  Everything else, Ask the Ghost included, is in this build.\n');
  // electron-builder wants something in the folder it ships as resources/creator.
  if (!fs.readdirSync(creatorStage).length) fs.writeFileSync(path.join(creatorStage, 'creator.txt'), 'Creator build.\n', 'utf8');
} else {
  fs.writeFileSync(path.join(creatorStage, 'customer.txt'), 'Customer build: no Ghost Pilot.\n', 'utf8');
}

// 2) electron-builder with named artifacts
const artifactName = `Lyricist ${fullVersion}${edition} Setup.\${ext}`;
const builderArgs = [
  'electron-builder',
  dirOnly ? '--win' : '--win',
  dirOnly ? 'dir' : 'nsis',
  `--config.directories.output=${JSON.stringify(desktopOut)}`,
  `--config.artifactName=${JSON.stringify(artifactName)}`,
  `--config.productName=Lyricist`,
  // Windows File Description / version strings
  `--config.buildVersion=${fullVersion}`,
];

// TEMP dirs on C: avoid OneDrive EPERM
const tempBuild = 'C:\\temp\\lyricist-build';
fs.mkdirSync(tempBuild, { recursive: true });
process.env.TEMP = tempBuild;
process.env.TMP = tempBuild;

run('npx', builderArgs);

// 3) Also rename/copy win-unpacked folder for clarity
const unpacked = path.join(desktopOut, 'win-unpacked');
const namedUnpacked = path.join(desktopOut, `Lyricist ${fullVersion}${edition}`);
if (fs.existsSync(unpacked)) {
  try {
    if (fs.existsSync(namedUnpacked)) {
      fs.rmSync(namedUnpacked, { recursive: true, force: true });
    }
    // Copy so electron-builder can still use win-unpacked next time
    // robocopy exit codes 0–7 = success (do not use run() which treats non-zero as fail)
    // Paths have spaces — quote for cmd; robocopy 0–7 = success
    const cmd = `robocopy "${unpacked}" "${namedUnpacked}" /E /NFL /NDL /NJH /NJS /nc /ns /np`;
    console.log(`> ${cmd}`);
    const rc = spawnSync(cmd, { stdio: 'inherit', shell: true });
    if ((rc.status ?? 0) > 7) {
      console.warn('robocopy failed with code', rc.status);
    }
  } catch (e) {
    console.warn('Could not copy named unpacked folder:', e.message);
  }
}

// 4) Bump for next release (after successful ship)
if (!noBump && forceSet == null) {
  writeBuildNum(buildNum + 1);
  console.log(`Next build will be ${baseVersion}.${pad(buildNum + 1)}`);
}

console.log(`
╔══════════════════════════════════════════════╗
║  SHIPPED: Lyricist ${fullVersion}${edition}${creator ? '  (Ghost ON: not for customers)' : ''}
║  Folder:  ${desktopOut}
║  Setup:   Lyricist ${fullVersion}${edition} Setup.exe
║  Run:     Lyricist ${fullVersion}${edition}\\Lyricist.exe
╚══════════════════════════════════════════════╝
`);
