#!/usr/bin/env node
/**
 * Lyricist release builder
 *
 * Bumps build-number.txt → 001, 002, 003…
 * Writes src/buildInfo.js
 * Vite build + electron-builder
 * Output names:
 *   Lyricist 4.2.0.001 Setup.exe
 *   Lyricist 4.2.0.001/   (win-unpacked copy, optional)
 *
 * Usage:
 *   node scripts/release.mjs              # bump + full installer
 *   node scripts/release.mjs --no-bump    # rebuild same build number
 *   node scripts/release.mjs --dir        # unpacked dir only (faster)
 *   node scripts/release.mjs --set 12     # force build number to 012
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { spawnSync } from 'child_process';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const BUILD_FILE = path.join(ROOT, 'build-number.txt');
const BUILD_INFO = path.join(ROOT, 'src', 'buildInfo.js');
const PKG_PATH = path.join(ROOT, 'package.json');

const args = process.argv.slice(2);
const noBump = args.includes('--no-bump');
const dirOnly = args.includes('--dir');
const setIdx = args.indexOf('--set');
const forceSet = setIdx >= 0 ? parseInt(args[setIdx + 1], 10) : null;

const pkg = JSON.parse(fs.readFileSync(PKG_PATH, 'utf8'));
const baseVersion = String(pkg.version || '4.2.0').split('.').slice(0, 3).join('.');

function readBuildNum() {
  try {
    const n = parseInt(String(fs.readFileSync(BUILD_FILE, 'utf8')).trim(), 10);
    return Number.isFinite(n) && n > 0 ? n : 1;
  } catch {
    return 1;
  }
}

function writeBuildNum(n) {
  fs.writeFileSync(BUILD_FILE, `${n}\n`, 'utf8');
}

function pad(n) {
  return String(n).padStart(3, '0');
}

let buildNum = readBuildNum();
if (forceSet != null && Number.isFinite(forceSet) && forceSet > 0) {
  buildNum = forceSet;
  writeBuildNum(buildNum);
} else if (!noBump) {
  // If file says 1 and we haven't released yet, use 1 first then next bump is 2.
  // Convention: bump BEFORE each release so first release is 001 when file starts at 0 or we use current then increment after.
  // User wants 001, 002, 003 on each executable turn-in.
  // On first run with file=1 → ship 001, then write 2 for next.
  // If re-running same day with --no-bump, keep number.
  // Default: use current number, then increment file for next time.
}

const buildPad = pad(buildNum);
const fullVersion = `${baseVersion}.${buildPad}`;

// UI always shows clean product version (4.2.0). Build pad is for EXE filenames only.
const buildInfoSrc = `// Auto-generated by scripts/release.mjs — do not hand-edit for releases.
// On-screen product version: ${baseVersion}
// Installer / folder name only: Lyricist ${fullVersion}
export const APP_VERSION = '${baseVersion}';
export const BUILD_NUMBER = '${buildPad}';
export const FULL_VERSION = '${fullVersion}';
/** Shown in UI — never includes .001/.002 build pad */
export const APP_TITLE = 'Lyricist ${baseVersion}';
export const WINDOW_TITLE = 'Lyricist ${baseVersion} Goes Quantum';
`;

fs.writeFileSync(BUILD_INFO, buildInfoSrc, 'utf8');
console.log(`\n═══ Lyricist release ${fullVersion} ═══\n`);

// Desktop output folder (user convention)
const desktopOut =
  process.env.LYRICIST_RELEASE_DIR ||
  path.join(
    process.env.USERPROFILE || process.env.HOME || ROOT,
    'OneDrive',
    'Desktop',
    'New Releases for Lyricist Goes Quantum'
  );

fs.mkdirSync(desktopOut, { recursive: true });

function run(cmd, cmdArgs, opts = {}) {
  console.log(`> ${cmd} ${cmdArgs.join(' ')}`);
  const r = spawnSync(cmd, cmdArgs, {
    cwd: ROOT,
    stdio: 'inherit',
    shell: true,
    env: {
      ...process.env,
      LYRICIST_FULL_VERSION: fullVersion,
      LYRICIST_BUILD: buildPad,
    },
    ...opts,
  });
  if (r.status !== 0) {
    console.error(`Command failed: ${cmd}`);
    process.exit(r.status || 1);
  }
}

// 1) Vite production build
run('npm', ['run', 'build']);

// 2) electron-builder with named artifacts
const artifactName = `Lyricist ${fullVersion} Setup.\${ext}`;
const builderArgs = [
  'electron-builder',
  dirOnly ? '--win' : '--win',
  dirOnly ? 'dir' : 'nsis',
  `--config.directories.output=${JSON.stringify(desktopOut)}`,
  `--config.artifactName=${JSON.stringify(artifactName)}`,
  `--config.productName=Lyricist`,
  // Windows File Description / version strings
  `--config.buildVersion=${fullVersion}`,
];

// TEMP dirs on C: avoid OneDrive EPERM
const tempBuild = 'C:\\temp\\lyricist-build';
fs.mkdirSync(tempBuild, { recursive: true });
process.env.TEMP = tempBuild;
process.env.TMP = tempBuild;

run('npx', builderArgs);

// 3) Also rename/copy win-unpacked folder for clarity
const unpacked = path.join(desktopOut, 'win-unpacked');
const namedUnpacked = path.join(desktopOut, `Lyricist ${fullVersion}`);
if (fs.existsSync(unpacked)) {
  try {
    if (fs.existsSync(namedUnpacked)) {
      fs.rmSync(namedUnpacked, { recursive: true, force: true });
    }
    // Copy so electron-builder can still use win-unpacked next time
    // robocopy exit codes 0–7 = success (do not use run() which treats non-zero as fail)
    // Paths have spaces — quote for cmd; robocopy 0–7 = success
    const cmd = `robocopy "${unpacked}" "${namedUnpacked}" /E /NFL /NDL /NJH /NJS /nc /ns /np`;
    console.log(`> ${cmd}`);
    const rc = spawnSync(cmd, { stdio: 'inherit', shell: true });
    if ((rc.status ?? 0) > 7) {
      console.warn('robocopy failed with code', rc.status);
    }
  } catch (e) {
    console.warn('Could not copy named unpacked folder:', e.message);
  }
}

// 4) Bump for next release (after successful ship)
if (!noBump && forceSet == null) {
  writeBuildNum(buildNum + 1);
  console.log(`Next build will be ${baseVersion}.${pad(buildNum + 1)}`);
}

console.log(`
╔══════════════════════════════════════════════╗
║  SHIPPED: Lyricist ${fullVersion}
║  Folder:  ${desktopOut}
║  Setup:   Lyricist ${fullVersion} Setup.exe
║  Run:     Lyricist ${fullVersion}\\Lyricist.exe
╚══════════════════════════════════════════════╝
`);
