// Auto-generated by scripts/release.mjs — do not hand-edit for releases.
// On-screen product version: 4.2.0
// Installer / folder name only: Lyricist 4.2.0.082
export const APP_VERSION = '4.2.0';
export const BUILD_NUMBER = '082';
export const FULL_VERSION = '4.2.0.082';
/** Shown in UI — never includes .001/.002 build pad */
export const APP_TITLE = 'Lyricist 4.2.0';
export const WINDOW_TITLE = 'Lyricist 4.2.0 Goes Quantum';
