// Auto-generated by scripts/release.mjs — do not hand-edit for releases.
// On-screen product version: 4.2.0
// Installer / folder name only: Lyricist 4.2.0.149
export const APP_VERSION = '4.2.0';
export const BUILD_NUMBER = '149';
export const FULL_VERSION = '4.2.0.149';
/** Shown in UI — never includes .001/.002 build pad */
/** The product name. Never carries a version — that is what APP_VERSION is for,
 *  and "Lyricist 4.2.0" as a NAME was the 420 joke the commercial refactor
 *  removed. Regenerating this file must not put it back. */
export const APP_TITLE = 'Lyricist Pro';
export const WINDOW_TITLE = 'Lyricist Pro';
